from .base import AbstractParser
from models.entry import SubtitleEntry, SubtitleFile
from models.enums import SubtitleFormat
from utils.time_utils import parse_ass_timestamp, format_ass_timestamp


ASS_EVENT_FORMAT = (
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
)

DEFAULT_ASS_HEADER = """[Script Info]
; Generated by Bilingual Subtitle Tool
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"""


def default_ass_header(target_format: SubtitleFormat = SubtitleFormat.ASS) -> str:
    if target_format == SubtitleFormat.SSA:
        return DEFAULT_ASS_HEADER.replace("ScriptType: v4.00+", "ScriptType: v4.00").replace(
            "[V4+ Styles]", "[V4 Styles]"
        )
    return DEFAULT_ASS_HEADER


def normalize_ass_header(header: str, target_format: SubtitleFormat) -> str:
    """Return a complete ASS/SSA header with one valid Events format line."""
    lower = header.lower() if header else ""
    has_style_section = "[v4+ styles]" in lower or "[v4 styles]" in lower
    if not header or "[events]" not in lower or "[script info]" not in lower or not has_style_section:
        return default_ass_header(target_format)

    normalized = header
    if target_format == SubtitleFormat.SSA:
        normalized = normalized.replace("[V4+ Styles]", "[V4 Styles]")
        normalized = normalized.replace("ScriptType: v4.00+", "ScriptType: v4.00")
    else:
        normalized = normalized.replace("[V4 Styles]", "[V4+ Styles]")
        normalized = normalized.replace("ScriptType: v4.00\n", "ScriptType: v4.00+\n")

    lines = normalized.rstrip().splitlines()
    events_index = next(
        (index for index, line in enumerate(lines) if line.strip().lower() == "[events]"),
        -1,
    )
    format_index = next(
        (
            index
            for index in range(events_index + 1, len(lines))
            if lines[index].strip().lower().startswith("format:")
        ),
        -1,
    )
    if format_index < 0:
        lines.insert(events_index + 1, ASS_EVENT_FORMAT)
    return "\n".join(lines)


class AssParser(AbstractParser):
    @staticmethod
    def parse(raw_text: str) -> SubtitleFile:
        entries = []
        in_events = False
        format_fields: list[str] = []
        header_lines = []

        for line in raw_text.split("\n"):
            stripped = line.strip()

            if not in_events:
                header_lines.append(line)
                if stripped.lower() == "[events]":
                    in_events = True
                continue

            if stripped.lower().startswith("format:"):
                fmt_str = stripped[len("Format:"):].strip()
                format_fields = [field.strip() for field in fmt_str.split(",")]
                header_lines.append(line)
                continue

            if stripped.startswith("Dialogue:") or stripped.startswith("Comment:"):
                content = stripped[stripped.index(":") + 1:].strip()
                fields = _split_ass_fields(content, len(format_fields))

                if len(fields) < 3:
                    header_lines.append(line)
                    continue

                field_map: dict[str, str] = {}
                for index, name in enumerate(format_fields):
                    field_map[name.lower()] = fields[index] if index < len(fields) else ""

                start_str = field_map.get("start", "")
                end_str = field_map.get("end", "")
                if not start_str or not end_str:
                    header_lines.append(line)
                    continue

                metadata: dict[str, str] = {
                    "layer": field_map.get("layer", "0"),
                    "style": field_map.get("style", ""),
                    "name": field_map.get("name", field_map.get("actor", "")),
                    "marginl": field_map.get("marginl", ""),
                    "marginr": field_map.get("marginr", ""),
                    "marginv": field_map.get("marginv", ""),
                    "effect": field_map.get("effect", ""),
                    "event_type": "Comment" if stripped.startswith("Comment:") else "Dialogue",
                }

                entries.append(
                    SubtitleEntry(
                        index=len(entries) + 1,
                        start_time=parse_ass_timestamp(start_str),
                        end_time=parse_ass_timestamp(end_str),
                        lines=field_map.get("text", "").split("\\N"),
                        metadata=metadata,
                    )
                )
            elif stripped:
                header_lines.append(line)

        lower = raw_text.lower()
        subtitle_format = (
            SubtitleFormat.SSA
            if "[v4 styles]" in lower and "[v4+ styles]" not in lower
            else SubtitleFormat.ASS
        )
        return SubtitleFile(
            entries=entries,
            format=subtitle_format,
            header="\n".join(header_lines),
        )

    @staticmethod
    def write(sub_file: SubtitleFile) -> str:
        target_format = (
            sub_file.format
            if sub_file.format in (SubtitleFormat.ASS, SubtitleFormat.SSA)
            else SubtitleFormat.ASS
        )
        header_lines = normalize_ass_header(sub_file.header, target_format).rstrip().splitlines()
        events_index = next(
            (index for index, line in enumerate(header_lines) if line.strip().lower() == "[events]"),
            -1,
        )
        format_index = next(
            (
                index
                for index in range(events_index + 1, len(header_lines))
                if header_lines[index].strip().lower().startswith("format:")
            ),
            -1,
        )
        if format_index < 0:
            header_lines.insert(events_index + 1, ASS_EVENT_FORMAT)
            format_index = events_index + 1

        format_fields = [
            field.strip()
            for field in header_lines[format_index].strip()[len("Format:"):].split(",")
        ]
        parts = list(header_lines)
        for entry in sub_file.entries:
            event_type = entry.metadata.get("event_type", "Dialogue")
            if event_type not in ("Dialogue", "Comment"):
                event_type = "Dialogue"
            parts.append(f"{event_type}: " + ",".join(_build_ass_fields(entry, format_fields)))
        return "\n".join(parts)


def _split_ass_fields(content: str, num_fields: int | None = None) -> list[str]:
    result = []
    current = ""
    index = 0
    splits_remaining = max(num_fields - 1, 0) if num_fields else -1

    while index < len(content):
        if content[index] == "\\" and index + 1 < len(content) and content[index + 1] == ",":
            current += ","
            index += 2
        elif splits_remaining == 0:
            current += content[index:]
            break
        elif content[index] == ",":
            result.append(current.strip())
            current = ""
            index += 1
            if splits_remaining > 0:
                splits_remaining -= 1
        else:
            current += content[index]
            index += 1

    result.append(current.strip())
    if num_fields:
        while len(result) < num_fields:
            result.append("")
    return result


def _escape_ass_text(text: str) -> str:
    return text.replace(",", "\\,")


def _build_ass_fields(entry: SubtitleEntry, format_fields: list[str]) -> list[str]:
    field_lower = [field.lower().strip() for field in format_fields]
    metadata = entry.metadata or {}
    values: dict[str, str] = {
        "text": "\\N".join(entry.lines) if entry.lines else "",
        "start": format_ass_timestamp(entry.start_time),
        "end": format_ass_timestamp(entry.end_time),
        "layer": str(metadata.get("layer", entry.index - 1 if entry.index > 0 else 0)),
        "style": str(metadata.get("style", "Default")),
        "name": str(metadata.get("name", metadata.get("actor", ""))),
        "actor": str(metadata.get("actor", metadata.get("name", ""))),
        "marginl": str(metadata.get("marginl", "0") or "0"),
        "marginr": str(metadata.get("marginr", "0") or "0"),
        "marginv": str(metadata.get("marginv", "0") or "0"),
        "effect": str(metadata.get("effect", "")),
    }

    result = []
    for field in field_lower:
        value = values.get(field, "")
        if field == "text":
            value = _escape_ass_text(value)
        result.append(value)
    return result
